---
deployment:
  tasks:
    - export DEPLOYPATH=/home/arie8572/public_html/
    - /bin/cp -r app $DEPLOYPATH
    - /bin/cp -r bootstrap $DEPLOYPATH
    - /bin/cp -r confiq $DEPLOYPATH
    - /bin/cp -r database $DEPLOYPATH
    # - /bin cp -R node_modules $DEPLOYPATH
    - /bin/cp -r public $DEPLOYPATH
    - /bin/cp -r resource $DEPLOYPATH
    - /bin/cp -r route $DEPLOYPATH
    - /bin/cp -r storage $DEPLOYPATH
    - /bin/cp -r test $DEPLOYPATH
    - /bin/cp -r vendor $DEPLOYPATH
    - /bin/cp .env $DEPLOYPATH
    - /bin/cp .env.example $DEPLOYPATH
    - /bin/cp composer.json $DEPLOYPATH
    - /bin/cp composer.lock $DEPLOYPATH
    - /bin/cp LICENSE $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp vite.config.js $DEPLOYPATH
    - /bin/cp phpunit.xml $DEPLOYPATH
    - /bin/cp artisan $DEPLOYPATH
    - /bin/cp .editorconfig $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp .gitattributes $DEPLOYPATH
